# Настройки по умолчанию
AGENT_COLOR = "#ee6c4d"
AGENT_SPEED = 8
AGENT_SIZE = 10
ENEMY_COLOR = "#e0fbfc"
ENEMY_SPEED = 8
ENEMY_SIZE = 5
SANDBOX_BACKGROUND_COLOR = "#293241"

NN_SHAPE = [16]
MUTATE_FUNC = "gauss"
MUTATE_FRACTION = 0.15
MUTATE_DEVIATION = 0.5
SCORE_LIMIT = 10000
BALLS = 30
POPULATION_SIZE = 80
CHILDS = 3
GENERATION_COUNT = 100
SANDBOX_WIDTH = 600
SANDBOX_HEIGHT = 600
RANDOM_STATE = None
